project_id = "zzsibjquwzcrsbdbqwog"

[functions.ai-assistant]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.admin-roles]
verify_jwt = false

[functions.send-recipe]
verify_jwt = false

[functions.adaptar-dieta]
verify_jwt = false
